ben's API changes
DSSD-Madison/gmu pull request #15
Opened 2024-11-25 05:19 UTC by adrian-brady

Ben's changes made to the older main reapplied to the new main (they have diverging histories due to me rebase merging my kendra search PR and then it getting squashed)

2024-11-25 20:25 UTC, adrian-brady commented
Overall things look good. I couldn't get the search bar to appear when testing myself, but the page loaded correctly otherwise. I am a bit confused about to the API. HTMX's power comes from the leveraging of HTTP requests and HTML, thus it would be best to use HTTP requests and responses and HTML in the responses as well.

2024-11-27 01:34 UTC, bengoh815 commented
# Decision Choices and Organization Summary

## Organizing and Documentation

### Routes
- Divided into two categories: APIs and pages, for clearer separation of concerns.
- Organized to call the respective api and pages packages for better modularity.

## Template Management

### Challenges
  - I had difficulty managing and importing templates using block, define, and template.
  - Current structure is functional but lacks clarity on how components integrate into pages.

### Views Organization
  - Current setup:
    - Separated into pages, components, and layouts directories for clarity.
    - **Pros**: Categories of files are grouped for easier maintenance.
    - **Cons**: Individual page components are scattered across directories.
  - Alternative Setup:
    - Organize by individual page:
    - Example:
    ```plaintext
    views/
      home/
        statistics.html
      search/
        search-bar.html
      results/
        filters.html
        book.html
    ```

    - **Pros**: All components for a single page are grouped together.
    - **Cons**: Different categories (e.g., layout, components) are separated, increasing directory depth.
 
## View and Template Structure

### Approach 1: Blanket Import
  - Import all templates or HTML files in views and resolve references dynamically.
  - **Pros**: Simplifies initial setup.
  - **Cons**:
      - Harder to trace component usage.
      - May load unnecessary templates, increasing overhead.
### Approach 2: Fine-Grained Import (Current)
  - Explicitly modify template imports whenever there are changes.
  - **Pros**: 
    - Provides granular control over templates
    - Wrong changes to template are not rendered immediately and will not crash and burn.
  - **Cons**: Developers must understand the integration logic for templates and components.
  - Should look into how templates should be managed, for easier integration. Back to Blanket Import?

## Suggestions for Asset Management

- Images: Needs better naming conventions or organize by type or use case (e.g., hero, icons, thumbnails).
- AWS Models: Consider moving AWS-related models into a dedicated directory for clarity:

## Miscellaneous

Search query not handled. Just basic GET Search page.
Look into some kind of linting or formatting for better code clarity

2024-11-27 02:38 UTC, sarthyparty requested changes
ok Ben, left a few comments to help you in the right direction. this is not a complete review and once you clean it up I can give better comments and help better, right now this is just general stuff.

You've done a lot of unnecessary work and you will need to fix that before this gets approved. I do like the filters UI  it does look good

2024-11-27 02:38 UTC, sarthyparty commented on routes/routes.go
> +	"github.com/DSSD-Madison/gmu/routes/api"
in golang, we organize imports like this:

system

external

internal

i'm not going to add a comment for all the places you need to fix this so look through your files

2024-11-27 02:38 UTC, sarthyparty commented on routes/routes.go
> +		API
this is not necessary, either just make a function that returns the mock data or use the actual API

2024-11-27 02:38 UTC, sarthyparty commented on tailwind.config.js
> +        "./views/*.html",
i don't think you need this

2024-11-27 02:38 UTC, sarthyparty commented on views/pages/home.html
> +{{ define "content" }}
let's call this an info page

2024-11-27 02:38 UTC, sarthyparty commented on views/pages/results.html
> +<div class="relative h-[300px]">
ok try to get everything that AJ has worked on involving results to work so we don't have to redo that

2024-11-27 02:38 UTC, sarthyparty commented on views/pages/book.html
> +  <p class="text-sm text-gray-500">{{ .Id }}</p>
What is the reason for Id?

2024-11-27 02:38 UTC, sarthyparty commented on CONTRIBUTING.md
> +
i'm not really sure if you want to keep this, this PR is not really for working on any documentation and i dont want to givw feedback on this

2024-11-27 02:38 UTC, sarthyparty commented on API.md
> +
we do not need this at all. we shouldnt have an APi for filters, we're using the kendra api

2024-11-27 02:38 UTC, sarthyparty commented on .gitignore
> +# ========================
whats with all the comments??

2024-12-03 21:01 UTC, closed without merging