Use new templating structure
DSSD-Madison/gmu pull request #20
Opened 2024-11-28 00:30 UTC by adrian-brady

Add templating structure @bengoh815 added in his API changes commit. 

This new templating method requires adding new `.html` files directly to a "template" definition in `models/templates.go`. This allows for defining different templates with the same defined name. 

Template sections are now, for the most part, defined using `define`. `define` does not immediately execute the template's HTML, adding it into the templates output. It defines a composable component which can be added into another section using `{{ template "name" .}}` or `{{ block "name" .}} default content {{ end }}`.

2024-11-28 03:33 UTC, bengoh815 reviewed
Other than the debug code in `models/templates.go`, I think it looks good!

2024-11-28 03:33 UTC, bengoh815 commented on models/templates.go
> +	log.Println("Rendering template:", name)
Should this be removed?

2024-11-28 05:15 UTC, sarthyparty commented
@adrian-brady I'll review this soon, but you'll have to run "git rebase main" in your branch before you can merge to resolve the conflict.

2024-11-28 17:36 UTC, sarthyparty commented
@adrian-brady why is this better than what we had before?

2024-11-28 17:45 UTC, adrian-brady commented
@sarthyparty it allows for better composition of templates. With the current template rendering method we could not define multiple blocks with the same name. This would make it impossible to reuse a base template for example.

A base template that wraps a block with HTML boilerplate could have a "content" block which could be composed with a "home" page or "search" page depending on what gets defined for a template key in the new template map. 

Lmk if that makes sense or if you have more questions.

2024-11-28 20:19 UTC, sarthyparty requested changes
looks pretty good. just make sure you get the rebase to work

2024-11-28 20:19 UTC, sarthyparty commented on models/templates.go
> +	return t.templates[name].Execute(w, data)
lets add some error handling here with a useful message so its easy to debug if we mess up with the key

2024-11-28 20:19 UTC, sarthyparty commented on views/book.html
> +{{ define "book-page" }}
I just realized that we're not even using this component. When you rebase and get all the new stuff into this PR then remove this file or replace this with the result-card

2024-11-28 20:20 UTC, sarthyparty commented
Feel free to ask me for help with this rebase, I'm fairly good with rebases and this seems simple enough

2024-11-29 05:00 UTC, vithul7 approved these changes
good to go.

2024-11-29 06:56 UTC, sarthyparty approved these changes

2024-11-29 18:34 UTC, merged